baseURL: 'https://makovako.xyz/blog/'
languageCode: 'en-us'
title: 'My new hugo site'
theme: 'makovako-blog-theme'
# theme: 'custom-theme'
copyright: 'Everything is mine'
paginate: 12
relativeURLs: true
uglyURLs: true
staticDir: static

taxonomies:
    category: categories
    tag: tags

languages:
    en:
        title: My blog
        weight: 1
        # staticDir: static
    sk:
        title: Môj blog
        # staticDir: static
        weight: 2